### ISSUE TITLE
Good Going/Suggestions

### ISSUE THREAD

**Issue by Ashwanidubeyiitb** [rohankalbag/fetch-my-memories#9]
Fixes:

Update Username: Please use the user's email ID as their username. It seems people are getting confused when trying to download, so this small change will help a lot.

CSS Improvements: Seniors have shared feedback about the formatting, and honestly, they have a point. The text is overlapping, the background feels unthemed, and the flow of the yearbook isn't as structured as it could be. Feed messages of any size are randomly appearing in the PDF, which is a bit chaotic.

While there might be a delay in delivery of yearbook, but imagine the happiness seniors would feel lifelong if their yearbook was beautifully designed with a theme-based flow, a gallery, and a "khazana of memories" instead of something that feels rushed and making feel shy on sharing with someone. The API part iwas straightforward no big deal with it, but creating something that truly captures their memories is what makes this special.

But yes as you said "It is a rudimentary, work in progress " so go ahead. Kudos and GG!!

**Comment by rohankalbag** [comment]
Thanks for the suggestions, have updated username to email for improved user experience

Regarding your second point, there is an issue tracking the same #1 and feel free to contribute if interested
